using System;
using UnityEngine;
using UnityEditor;
using System.IO;
using System.Linq;
using UnityEditorInternal;

namespace PokaiLand.Utility.Editor
{
    public class LayerConstGenerator : EditorWindow
    {
        private const string FilePath = "Assets/Projects/1_Scripts/Utility/Constants/LayerConstants.cs";
    
        [MenuItem("Tools/Generate Layer Constants")]
        private static void GenerateConstants()
        {
            var layers = InternalEditorUtility.layers;
            var constContent = GenerateConstContent(layers);
        
            var directory = Path.GetDirectoryName(FilePath);
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory ?? throw new InvalidOperationException());
            }
        
            File.WriteAllText(FilePath, constContent);
            AssetDatabase.Refresh();
        
            Debug.Log($"Layer constants generated at {FilePath}");
        }
    
        private static string GenerateConstContent(string[] layers)
        {
            var constEntries = layers.Select((layer, index) => 
                $"    public const int {MakeValidName(layer)} = {index};");
        
            var maskEntries = layers.Select((layer, index) => 
                $"    public static readonly int {MakeValidName(layer)}Mask = 1 << {index};");

            return $@"// Generated by LayerConstGenerator
using UnityEngine;

public static class Layers
{{
{string.Join("\n", constEntries)}

    // Layer masks
{string.Join("\n", maskEntries)}
}}";
        }
    
        private static string MakeValidName(string layerName)
        {
            return string.Join("_", layerName.Split(' ', '-', '/')
                .Select(s => char.IsLetter(s[0]) ? s : "_" + s));
        }
    }
}