// Generated by LayerConstGenerator
using UnityEngine;

public static class Layers
{
    public const int Default = 0;
    public const int TransparentFX = 1;
    public const int Ignore_Raycast = 2;
    public const int Ground = 3;
    public const int Water = 4;
    public const int UI = 5;
    public const int Player = 6;
    public const int OtherPlayer = 7;
    public const int Invisible = 8;

    // Layer masks
    public static readonly int DefaultMask = 1 << 0;
    public static readonly int TransparentFXMask = 1 << 1;
    public static readonly int Ignore_RaycastMask = 1 << 2;
    public static readonly int GroundMask = 1 << 3;
    public static readonly int WaterMask = 1 << 4;
    public static readonly int UIMask = 1 << 5;
    public static readonly int PlayerMask = 1 << 6;
    public static readonly int OtherPlayerMask = 1 << 7;
    public static readonly int InvisibleMask = 1 << 8;
}